# Generated by Django 4.2.7 on 2024-01-09 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_alter_otwdc_receiver_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inwdc',
            name='cust_id',
            field=models.ForeignKey(blank=True, db_column='cust_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='server.customermaster'),
        ),
    ]
