# Generated by Django 4.2.7 on 2024-01-12 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_alter_inwdc_cust_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='po',
            name='quote_ref_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
